name: lfc
version: '0.1.0.0'
synopsis: An experiment with STLC, recursion schemes and Cofree.
description: Please see README.md
category: Development
author: Romain Ruetschi
maintainer: romain.ruetschi@gmail.com
copyright: 2017 Romain Ruetschi
license: BSD3
github: romac/lfc-haskell

dependencies:
  - ansi-wl-pprint 
  - base >=4.7 && <5
  - comonad
  - containers
  - deriving-compat
  - free
  - freer
  - protolude
  - recursion-schemes
  - semigroups

default-extensions:
  - NoImplicitPrelude

library:
  source-dirs: src

