name: lambda
version: '0.1.0.0'
synopsis: Just messing around with recursion schemes and Cofree.
description: Please see README.md
category: Development
author: Romain Ruetschi
maintainer: romain.ruetschi@gmail.com
copyright: 2016 Romain Ruetschi
license: BSD3
github: romac/lambda

dependencies:
  - ansi-wl-pprint 
  - base >=4.7 && <5
  - comonad
  - containers
  - deriving-compat
  - free
  - mtl
  - protolude
  - recursion-schemes
  - transformers

default-extensions:
  - NoImplicitPrelude

library:
  source-dirs: src

